Experiment 'pythonPromptNewToolsExt' is active
> conda info --json
Python interpreter path: /usr/bin/python3
[ERROR 2023-3-5 1:13:13.745]: readdir() failed for "/var/cache/ldconfig" (Error: EACCES: permission denied, scandir '/var/cache/ldconfig')
[ERROR 2023-3-5 1:13:13.746]: readdir() failed for "/var/cache/pollinate" (Error: EACCES: permission denied, scandir '/var/cache/pollinate')
[ERROR 2023-3-5 1:13:13.754]: readdir() failed for "/var/cache/private" (Error: EACCES: permission denied, scandir '/var/cache/private')
[ERROR 2023-3-5 1:13:13.758]: readdir() failed for "/var/lib/amazon" (Error: EACCES: permission denied, scandir '/var/lib/amazon')
[ERROR 2023-3-5 1:13:13.826]: readdir() failed for "/var/lib/polkit-1" (Error: EACCES: permission denied, scandir '/var/lib/polkit-1')
> /bin/python -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-5 1:13:13.853]: readdir() failed for "/var/lib/private" (Error: EACCES: permission denied, scandir '/var/lib/private')
> /bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-5 1:13:13.874]: readdir() failed for "/var/lib/udisks2" (Error: EACCES: permission denied, scandir '/var/lib/udisks2')
[ERROR 2023-3-5 1:13:13.880]: Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
> /bin/python ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
> /usr/bin/python -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-5 1:13:13.899]: readdir() failed for "/var/log/amazon" (Error: EACCES: permission denied, scandir '/var/log/amazon')
[ERROR 2023-3-5 1:13:13.901]: readdir() failed for "/var/log/private" (Error: EACCES: permission denied, scandir '/var/log/private')
> /usr/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-5 1:13:13.913]: Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
> /usr/bin/python ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-5 1:13:13.928]: readdir() failed for "/var/spool/rsyslog" (Error: EACCES: permission denied, scandir '/var/spool/rsyslog')
[ERROR 2023-3-5 1:13:13.930]: readdir() failed for "/var/tmp/systemd-private-e56d4eb3ba6940e0b1a4eecee152b3cb-ModemManager.service-5icDVi" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-e56d4eb3ba6940e0b1a4eecee152b3cb-ModemManager.service-5icDVi')
[ERROR 2023-3-5 1:13:13.930]: readdir() failed for "/var/tmp/systemd-private-e56d4eb3ba6940e0b1a4eecee152b3cb-apache2.service-dMQBph" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-e56d4eb3ba6940e0b1a4eecee152b3cb-apache2.service-dMQBph')
[ERROR 2023-3-5 1:13:13.930]: readdir() failed for "/var/tmp/systemd-private-e56d4eb3ba6940e0b1a4eecee152b3cb-systemd-logind.service-RROgvj" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-e56d4eb3ba6940e0b1a4eecee152b3cb-systemd-logind.service-RROgvj')
[ERROR 2023-3-5 1:13:13.931]: readdir() failed for "/var/tmp/systemd-private-e56d4eb3ba6940e0b1a4eecee152b3cb-systemd-resolved.service-I8rcyg" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-e56d4eb3ba6940e0b1a4eecee152b3cb-systemd-resolved.service-I8rcyg')
[ERROR 2023-3-5 1:13:13.934]: readdir() failed for "/var/tmp/systemd-private-e56d4eb3ba6940e0b1a4eecee152b3cb-systemd-timesyncd.service-RCGbQh" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-e56d4eb3ba6940e0b1a4eecee152b3cb-systemd-timesyncd.service-RCGbQh')
Starting Pylance language server.
